# Generated by Django 2.2.6 on 2020-05-09 08:35

import api.helpers
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('note_type', models.CharField(choices=[('NA', 'Not Available')], default='NA', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='NoteAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('attachment', models.FileField(upload_to=api.helpers.PathAndRename('piper/note-attachments'))),
                ('note_attachment_type', models.CharField(choices=[('NA', 'Not Available')], default='NA', max_length=2)),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Note')),
            ],
        ),
    ]
