# Generated by Django 2.2.12 on 2020-05-09 12:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 12, 44, 6, 91003)),
        ),
        migrations.AddField(
            model_name='note',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('MM', 'Minutes of Meeting'), ('RB', 'Business Requirements'), ('RU', 'User Requirements'), ('RS', 'System Requirements'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
        migrations.CreateModel(
            name='NoteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('text_note', models.TextField()),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Note')),
            ],
        ),
    ]
