# Generated by Django 2.2.12 on 2020-05-09 16:57

import api.helpers
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200509_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteChart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('chart_text', models.TextField()),
                ('chart_svg', models.FileField(upload_to=api.helpers.PathAndRename('piper/note-charts'))),
                ('chart_png', models.FileField(upload_to=api.helpers.PathAndRename('piper/note-charts'))),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Note')),
            ],
        ),
    ]
