# Generated by Django 2.2.12 on 2020-05-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_notechart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notechart',
            name='chart_png',
        ),
        migrations.RemoveField(
            model_name='notechart',
            name='chart_svg',
        ),
        migrations.AddField(
            model_name='noteattachment',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notechart',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='noteitem',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
