# Generated by Django 2.2.6 on 2020-05-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_medium_type',
            field=models.CharField(choices=[('PH', 'Phone'), ('PY', 'Physical'), ('VD', 'Video'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
    ]
