# Generated by Django 2.2.12 on 2020-05-09 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0002_auto_20200509_1244'),
        ('meetings', '0002_meeting_meeting_medium_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='notes',
            field=models.ManyToManyField(to='notes.Note'),
        ),
        migrations.AddField(
            model_name='meetinginvitation',
            name='invitee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetinginvitation',
            name='invitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitor', to=settings.AUTH_USER_MODEL),
        ),
    ]
