# Generated by Django 2.2.12 on 2020-05-16 14:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('EP', 'E-Perolehan'), ('T2', 'Tender2U'), ('TD', 'Tender Direct'), ('NA', 'Not Available')], default='NA', max_length=2)),
            ],
        ),
    ]
