# Generated by Django 2.2.12 on 2020-05-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='submission_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
