# Generated by Django 2.2.12 on 2020-05-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
