# Generated by Django 2.2.12 on 2020-05-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20200516_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
