# Generated by Django 2.2.12 on 2020-05-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20200516_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('AR', 'Archive'), ('CR', 'Created'), ('SM', 'Submission')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='notification',
            name='source',
            field=models.CharField(choices=[('EP', 'e-Perolehan'), ('T2', 'Tender2U'), ('TD', 'Tender Direct'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
    ]
