# Generated by Django 2.2.12 on 2020-05-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20200516_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='briefing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='briefing_required',
            field=models.CharField(choices=[('TR', 'True'), ('FL', 'False')], default='FL', max_length=2),
        ),
        migrations.AddField(
            model_name='notification',
            name='purchase_required',
            field=models.CharField(choices=[('TR', 'True'), ('FL', 'False')], default='FL', max_length=2),
        ),
    ]
