# Generated by Django 2.2.12 on 2020-05-17 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_auto_20200510_1322'),
        ('notifications', '0008_remove_notification_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation'),
        ),
    ]
