# Generated by Django 2.2.12 on 2020-05-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_notification_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
