# Generated by Django 2.2.12 on 2020-05-19 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_historicalorganisation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0011_auto_20200517_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalNotification',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('project', models.CharField(max_length=255)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('briefing_required', models.CharField(choices=[('TR', 'True'), ('FL', 'False')], default='FL', max_length=2)),
                ('briefing_date', models.DateTimeField(blank=True, null=True)),
                ('purchase_required', models.CharField(choices=[('TR', 'True'), ('FL', 'False')], default='FL', max_length=2)),
                ('source', models.CharField(choices=[('EP', 'e-Perolehan'), ('T2', 'Tender2U'), ('TD', 'Tender Direct'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('status', models.CharField(choices=[('AR', 'Archive'), ('CR', 'Created'), ('SM', 'Submission')], default='CR', max_length=2)),
                ('created_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisations.Organisation')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical notification',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
