# Generated by Django 2.2.12 on 2020-05-19 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='document_type',
            new_name='deployment_type',
        ),
    ]
