# Generated by Django 2.2.12 on 2020-05-09 16:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200509_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSoftwareModule',
            fields=[
                ('project_work_type', models.CharField(choices=[('NA', 'Not Available')], default='NA', max_length=2)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTradingModule',
            fields=[
                ('project_work_type', models.CharField(choices=[('NA', 'Not Available')], default='NA', max_length=2)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectWorkModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('project_work_type', models.CharField(choices=[('NA', 'Not Available')], default='NA', max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectRequirementLog',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('NA', 'Not Available')], default='NA', max_length=2),
        ),
    ]
