# Generated by Django 2.2.12 on 2020-05-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='enabled',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('AN', 'Analyst'), ('DE', 'Developer'), ('PM', 'Project Manager'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
    ]
