# Generated by Django 2.2.12 on 2020-05-10 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_auto_20200509_1248'),
        ('users', '0002_auto_20200509_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation'),
        ),
    ]
