# Generated by Django 2.2.12 on 2020-05-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_organisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Organisation',
            new_name='organisation',
        ),
    ]
