# Generated by Django 2.2.12 on 2020-05-11 14:36

import api.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200510_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=api.helpers.PathAndRename('piper/profile-pictures')),
        ),
    ]
