# Generated by Django 2.2.12 on 2020-05-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireframes', '0002_auto_20200519_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='wireframe',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
