# Generated by Django 2.2.12 on 2020-05-17 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20200517_0327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='name',
            new_name='codename',
        ),
    ]
