# Generated by Django 2.2.12 on 2020-05-17 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_auto_20200510_1322'),
        ('submissions', '0003_auto_20200517_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation'),
        ),
        migrations.AddField(
            model_name='submission',
            name='project',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
