# Generated by Django 2.2.12 on 2020-05-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_auto_20200517_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontask',
            name='task_status',
            field=models.CharField(choices=[('CR', 'Created'), ('AS', 'Assigned'), ('MK', 'In Progress'), ('MR', 'In Rectification'), ('CC', 'To Review'), ('CM', 'Completed')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='submission',
            name='codename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='submissiontask',
            name='task_type',
            field=models.CharField(choices=[('CP', 'Company Details'), ('PP', 'Proposal'), ('PT', 'Prototype'), ('VD', 'Video'), ('WF', 'Wireframe'), ('NA', 'Not Availabl')], default='NA', max_length=2),
        ),
    ]
