# Generated by Django 2.2.12 on 2020-05-19 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_historicalorganisation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0012_historicalnotification'),
        ('submissions', '0005_auto_20200517_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSubmissionTask',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('task_type', models.CharField(choices=[('CP', 'Company Details'), ('PP', 'Proposal'), ('PT', 'Prototype'), ('VD', 'Video'), ('WF', 'Wireframe'), ('NA', 'Not Availabl')], default='NA', max_length=2)),
                ('task_status', models.CharField(choices=[('CR', 'Created'), ('AS', 'Assigned'), ('MK', 'In Progress'), ('MR', 'In Rectification'), ('CC', 'To Review'), ('CM', 'Completed')], default='NA', max_length=2)),
                ('checker_by_date', models.DateTimeField(blank=True, null=True)),
                ('maker_by_date', models.DateTimeField(blank=True, null=True)),
                ('checker_real_date', models.DateTimeField(blank=True, null=True)),
                ('maker_real_date', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('checker', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('maker', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='notifications.Notification')),
            ],
            options={
                'verbose_name': 'historical submission task',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSubmissionDocument',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('document_file', models.TextField(max_length=100, null=True)),
                ('document_type', models.CharField(choices=[('PD', 'Provided'), ('RV', 'Revised Document'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical submission document',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSubmission',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('codename', models.CharField(max_length=255, null=True)),
                ('project', models.CharField(max_length=255, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CR', 'Created'), ('FL', 'Failed To Submit'), ('IP', 'In Progress'), ('RJ', 'Rejected'), ('SM', 'Submitted')], default='CR', max_length=2)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisations.Organisation')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='notifications.Notification')),
            ],
            options={
                'verbose_name': 'historical submission',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
