# Generated by Django 2.2.12 on 2020-05-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Func',
            new_name='Function',
        ),
    ]
