# Generated by Django 2.2.12 on 2020-05-17 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submission',
            new_name='Presentation',
        ),
    ]
