# Generated by Django 2.2.12 on 2020-05-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20200519_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('DP', 'Deployment Plan'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
    ]
