# Generated by Django 2.2.12 on 2020-05-09 12:44

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='organisation',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2020, 5, 9, 12, 44, 6, 85695)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisation_type',
            field=models.CharField(choices=[('GO', 'Government'), ('LC', 'Local Authority'), ('ER', 'Enterprise'), ('SM', 'SME Company'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='organisation',
            name='short_name',
            field=models.CharField(default='null', max_length=12),
            preserve_default=False,
        ),
    ]
