# Generated by Django 2.2.12 on 2020-05-10 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_auto_20200509_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='full_name',
            new_name='name',
        ),
    ]
